name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild clean build test -project UIDesignPatternsChallenge.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" ONLY_ACTIVE_ARCH=YES
